general {
        colors = true
        interval = 1
	color_good = "#666666"
	color_degraded = "#aeaeae"
	color_bad = "#c00000"
	color_separator = "#00cc00"
}

order += "wireless wlp3s0"
order += "ethernet eth0"
order += "battery 0"
order += "tztime local"

wireless wlp3s0 {
        format_up = "%quality %essid "
        format_down = ""
}

ethernet eth0 {
        # if you use %speed, i3status requires the cap_net_admin capability
        format_up = ""
        format_down = " "
}

battery 0 {
        format = "%status %percentage %remaining %emptytime"
        format_down = "No battery"
        status_chr = ""
        status_bat = ""
        status_unk = ""
        status_full = "☻"
        path = "/sys/class/power_supply/BAT%d/uevent"
        low_threshold = 10
}

tztime local {
        format = "Week %V - %Y%m%d - %H:%M:%S"
}

disk "/" {
        format = "%free"
}

