#!/bin/bash

export EDITOR=vim
export GOPATH=$HOME/go
export GOBIN=$HOME/go/bin
export MYSCRIPTS=$HOME/bin


export NVM_DIR="$HOME/.nvm"
export FLATPAK_BIN_DIR="/var/lib/flatpak/exports/bin/" # so rofi can launch flatpaks as well
export ROFI_2004_BUGFIX="/var/lib/flatpak/exports/share/applications" #ub 20.04 changed XDG_DATA_DIRS

# Use rg if we have it, else tell fzf we want to show hidden files with find
command -v rg >/dev/null 2>&1 && export FZF_DEFAULT_COMMAND="rg --files --hidden"
command -v rg >/dev/null 2>&1 || export FZF_DEFAULT_COMMAND="find -L"

[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

export PATH=$PATH:$GOPATH:$GOBIN:$MYSCRIPTS:$FLATPAK_BIN_DIR
export XDG_DATA_DIRS=$XDG_DATA_DIRS:$ROFI_2004_BUGFIX

#if command -v tmux tmux &> /dev/null && [ -z "$TMUX" ]; then
#	tmux attach -t default || tmux new -s default
#fi

